# Generated by Django 2.0.3 on 2018-04-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0002_auto_20180410_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storiebed',
            old_name='project_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='storiebed',
            old_name='new_project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='storiebed',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='storiebed',
            name='new_project_file',
        ),
        migrations.AddField(
            model_name='storiebed',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
